/*
 * PERIPH_USED.h
 *
 *  Created on: Oct 18, 2022
 *      Author: anh
 */

#ifndef PERIPH_USED_H_
#define PERIPH_USED_H_



/* PERIPHERAL ENABLE */
#define ENABLE_RCC
#define ENABLE_SYSTEMTICK
#define ENABLE_LOG
#define ENABLE_GPIO
#define ENABLE_DMA
#define ENABLE_USART
#define ENABLE_I2C

/* EXTI ENABLE */
//#define ENABLE_EXTI0
//#define ENABLE_EXTI1
//#define ENABLE_EXTI2
#define ENABLE_EXTI3
//#define ENABLE_EXTI4
//#define ENABLE_EXTI9_5
//#define ENABLE_EXTI15_10

/* DMA STREAM ENABLE */
//#define ENABLE_DMA1_STREAM0
//#define ENABLE_DMA1_STREAM1
//#define ENABLE_DMA1_STREAM2
//#define ENABLE_DMA1_STREAM3
#define ENABLE_DMA1_STREAM4
//#define ENABLE_DMA1_STREAM5
//#define ENABLE_DMA1_STREAM6
//#define ENABLE_DMA1_STREAM7
//
#define ENABLE_DMA2_STREAM0
//#define ENABLE_DMA2_STREAM1
//#define ENABLE_DMA2_STREAM2
//#define ENABLE_DMA2_STREAM3
//#define ENABLE_DMA2_STREAM4
//#define ENABLE_DMA2_STREAM5
//#define ENABLE_DMA2_STREAM6
#define ENABLE_DMA2_STREAM7



#endif /* PERIPH_USED_H_ */
